In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/online_retail.csv", encoding="ISO-8859-1")

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2022-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2022-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 69.3 MB

In [6]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [7]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(5268)

In [9]:
df.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
175355,551954,22980,PANTRY SCRUBBING BRUSH,2,2023-05-05 12:13:00,1.65,14515.0,United Kingdom
356754,568059,23184,BULL DOG BOTTLE OPENER,2,2023-09-23 12:58:00,4.95,13097.0,United Kingdom
417513,572662,23117,POPPY FIELDS CHOPPING BOARD,1,2023-10-25 12:54:00,4.95,15443.0,United Kingdom
149365,549291,22983,CARD BILLBOARD FONT,12,2023-04-07 19:05:00,0.42,16261.0,United Kingdom
477375,577057,21724,PANDA AND BUNNIES STICKER SHEET,2,2023-11-17 14:26:00,0.85,12748.0,United Kingdom
241976,558263,23306,SET OF 36 DOILIES PANTRY DESIGN,144,2023-06-28 08:50:00,1.25,14646.0,Netherlands
419691,572853,22173,METAL 4 HOOK HANGER FRENCH CHATEAU,8,2023-10-26 12:28:00,3.29,17712.0,United Kingdom
37275,539455,90160C,TURQ+RED BOUDICCA LARGE BRACELET,1,2022-12-17 17:17:00,6.95,12748.0,United Kingdom
46290,540352,22134,MINI LADLE LOVE HEART RED,1,2023-01-06 14:27:00,0.43,NaN,United Kingdom
70916,542107,21657,MILK BOTTLE WITH GLASS STOPPER,1,2023-01-25 13:38:00,6.95,16222.0,United Kingdom

In [10]:
df.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [11]:
clean_df = pd.read_csv("../data/processed/cleaned_online_retail.csv")
clean_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2022-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2022-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [12]:
clean_df.shape

(392692, 9)

In [13]:
clean_df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalAmount    0
dtype: int64

In [14]:
clean_df.duplicated().sum()

np.int64(0)

In [15]:
clean_df.describe()

,InvoiceNo,Quantity,UnitPrice,CustomerID,TotalAmount
count,392692.000000,392692.000000,392692.000000,392692.000000,392692.000000
mean,560590.875047,13.119702,3.125914,15287.843865,22.631500
std,13087.063759,180.492832,22.241836,1713.539549,311.099224
min,536365.000000,1.000000,0.001000,12346.000000,0.001000
25%,549234.000000,2.000000,1.250000,13955.000000,4.950000
50%,561874.000000,6.000000,1.950000,15150.000000,12.450000
75%,572061.000000,12.000000,3.750000,16791.000000,19.800000
max,581587.000000,80995.000000,8142.750000,18287.000000,168469.600000

In [16]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 392692 entries, 0 to 392691
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  int64
 1   StockCode    392692 non-null  str
 2   Description  392692 non-null  str
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  str
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  float64
 7   Country      392692 non-null  str
 8   TotalAmount  392692 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 50.9 MB