In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
rfm = pd.read_csv("../data/processed/rfm_table.csv")

rfm.head()

   CustomerID  Recency  Frequency  Monetary
0     12346.0      326          1  77183.60
1     12347.0        2          7   4310.00
2     12348.0       75          4   1797.24
3     12349.0       19          1   1757.55
4     12350.0      310          1    334.40

In [3]:
rfm.describe()

         CustomerID      Recency    Frequency       Monetary
count   4338.000000  4338.000000  4338.000000    4338.000000
mean   15300.408022    92.536422     4.272015    2048.688081
std     1721.808492   100.014169     7.697998    8985.230220
min    12346.000000     1.000000     1.000000       3.750000
25%    13813.250000    18.000000     1.000000     306.482500
50%    15299.500000    51.000000     2.000000     668.570000
75%    16778.750000   142.000000     5.000000    1660.597500
max    18287.000000   374.000000   209.000000  280206.020000

In [4]:
rfm.sort_values(
    "Monetary",
    ascending=False
).head(10)

      CustomerID  Recency  Frequency   Monetary
1689     14646.0        2         73  280206.02
4201     18102.0        1         60  259657.30
3728     17450.0        8         46  194390.79
3008     16446.0        1          2  168472.50
1879     14911.0        1        201  143711.17
55       12415.0       24         21  124914.53
1333     14156.0       10         55  117210.08
3771     17511.0        3         31   91062.38
2702     16029.0       39         63   80850.84
0        12346.0      326          1   77183.60

In [5]:
rfm.sort_values(
    "Frequency",
    ascending=False
).head(10)

      CustomerID  Recency  Frequency   Monetary
326      12748.0        1        209   33053.19
1879     14911.0        1        201  143711.17
4010     17841.0        2        124   40519.84
562      13089.0        3         97   58762.08
1661     14606.0        1         93   12076.15
2176     15311.0        1         91   60632.75
481      12971.0        4         86   11189.91
1689     14646.0        2         73  280206.02
2702     16029.0       39         63   80850.84
795      13408.0        2         62   28117.04

In [6]:
rfm.sort_values(
    "Recency"
).head(10)

      CustomerID  Recency  Frequency  Monetary
3662     17364.0        1         11   4462.68
71       12433.0        1          7  13375.87
934      13599.0        1         21   5149.92
892      13536.0        1          7   3444.39
3366     16933.0        1          2    563.23
3823     17581.0        1         25  11025.24
2611     15898.0        1          5   1383.83
3333     16892.0        1          5    518.19
3868     17644.0        1         11   2895.64
2620     15910.0        1          8   1228.88

# RFM Analysis

### Business Insights

**Recency**
- Customers with lower Recency values purchased more recently.
- These customers are more engaged and likely to respond to promotions.

**Frequency**
- Customers with high purchase frequency demonstrate loyalty.
- Retaining these customers should be a business priority.

**Monetary**
- High Monetary customers contribute a significant portion of total revenue.
- Premium offers and personalized marketing campaigns should target these customers.

### Why RFM Matters

RFM combines customer purchase behavior into three measurable metrics. These features will be standardized and used as inputs for the KMeans clustering algorithm to create actionable customer segments.